### ISSUE TITLE
local pdb files as input?

### ISSUE THREAD

**Issue by DaHenz** [veghen/ProRefiner#1]
Hi,
Thank you for your astonishing work. I am currently experimenting with various sequence design tools for de novo protein design. I am very keen to know if I can use a local PDB file as input for ProRefiner？

**Comment by veghen** [comment]
Hi, thank you for your interest in our work. I have updated the code for inference from local PDB files. Hope this helps

**Comment by DaHenz** [comment]
> Hi, thank you for your interest in our work. I have updated the code for inference from local PDB files. Hope this helps

Thank you a lot for your response and update; it is sure to be extremely helpful. Sofar, I haven't noticed any changes in the code on GitHub. Could you indicate where the updated code can be found?

**Comment by veghen** [comment]
It's in the latest commit of this repository (https://github.com/veghen/ProRefiner). Can you see the following change in README?
<img width="434" alt="截屏2023-11-28 上午11 07 11" src="https://github.com/veghen/ProRefiner/assets/43173020/7a27076f-7919-4bd0-a3ea-66bfc6ae9532">

**Comment by DaHenz** [comment]
> It's in the latest commit of this repository (https://github.com/veghen/ProRefiner). Can you see the following change in README? <img alt="截屏2023-11-28 上午11 07 11" width="434" src="https://private-user-images.githubusercontent.com/43173020/286103072-7a27076f-7919-4bd0-a3ea-66bfc6ae9532.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzE2MDksIm5iZiI6MTcwMTE3MTMwOSwicGF0aCI6Ii80MzE3MzAyMC8yODYxMDMwNzItN2EyNzA3NmYtNzkxOS00YmQwLWEzZWEtNjZiZmM2YWU5NTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDExMzUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NGY2ODEyOWVhMTZiZjk1MTRiMWY2YTdiNDI5NjBlOWQ2MWNjYjBjN2Q3NjY5MTcwNTUwNGEyYTlmYWJiNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZCjkyXUY6a-LsMbJhD0aDnG8n79eklQ396FN1UbwKAY">

All updates can be found now, and the instructions in README are very clear!  Thanks again!
