### ISSUE TITLE
ProRefiner change more than desired residues while doing partial design.

### ISSUE THREAD

**Issue by DaHenz** [veghen/ProRefiner#3]
Hi, I tried to test a partial design with the ProRefiner, whereas I want to design one AA in one chain from a pdb. Interestingly, in the output from MPNN, the desired residue was changed, But in ProRefiner two residues were changed. 

python run.py input/test8.pdb B 7

Recovery and nssr are computed based on designable residues with coordinates only.

Design 1 residues from input/test8.pdb chain B with length 15

native sequence:
GSARQE**N**RKEARQEG

sequence by ProteinMPNN: (recovery: 0.000	nssr: 0.000)
GSARQE**T**RKEARQEG

sequence by ProRefiner: (recovery: 0.000	nssr: 100.000)
GSARQE**S**R**L**EARQEG

**Comment by veghen** [comment]
Sorry for the mistake. The model performance is evaluated only on designable residues, so the non-designable part was initially overlooked in ProRefiner's output and it doesn't influence the evaluation results. I have fixed this by replacing the non-designable part with ground truth sequence in the output. Please check the latest commit. Sorry again and thank you very much for pointing this out.
